PYTHON_HOST = "localhost"
PYTHON_PORT = 5000
NIVEL_LOGS = "INFO"
DIRECTORIO_LOGS = "logs"

PAG_IMAGENES_URL = "https://image.tmdb.org/t/p/w500"

PAG_PELICULAS_URL = "https://api.themoviedb.org/3"
PAG_PELICULAS_API_KEY = "4294d227a0bf641e389362f06c10279f"
PAG_PELICULAS_IDIOMA = "es-MX"

DIRECTORIO_PRODUCE = "produce"
DIRECTORIO_CONSUME = "consume"

DIRECTORIO_QR = f"{DIRECTORIO_PRODUCE}/qr"
DIRECTORIO_DB = f"{DIRECTORIO_PRODUCE}/db"

DIRECTORIO_IMG_CINEMA = f"{DIRECTORIO_CONSUME}/img"
